# Generated by Django 4.2.5 on 2023-09-21 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
