# Generated by Django 4.2.5 on 2023-09-21 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0004_picture_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='title',
        ),
    ]
